### PR TITLE
Prevent lot size error

### LINKED ISSUE #294: Error when going straight to /deposit/new:  "Lot size 0 is not permitted...."
### Description:
When going straight to the url

`dapp.test.tbtc.network/deposit/new`

an error message appears:

`Lot size 0 is not permitted; only one of 100000,1000000,10000000,20000000,50000000,100000000 can be used.`

This message appears even before being given the option to choose a lot size.

### Steps to reproduce the behavior:

1. Go to https://dapp.test.tbtc.network/deposit/new. The page that appears shows step 2/5 Initiating deposit.
2. Click on 'Connect to a Wallet', select MetaMask. If not logged into MetaMask, login/unlock MetaMask.
3. The page almost immediately shows:

`Error initiating deposit`

and

`Lot size 0 is not permitted; only one of 100000,1000000,10000000,20000000,50000000,100000000 can be used.`

### Expected behavior:
When vistiting this URL, the app ought to recognise that I haven't chosen a lot size yet, and then give me the opportunity to choose a valid lot size. Or it could redirect me to dapp.test.tbtc.network if it can accurately identify that I haven't selected a lot size or completed step 1/5.

### Environment details:
OS: Windows 10 Pro, Version 1909, build 18363.959, 64 bit OS  
Web Browser: Google Chrome, Version 84.0.4147.89 (Official Build) (64-bit)  
Wallet: Metamask (Chrome extension), Version 8.0.5

### Screenshots
Console log file: 
[dapp.test.tbtc.network-1595562195620.log](https://github.com/keep-network/tbtc-dapp/files/4970103/dapp.test.tbtc.network-1595562195620.log)
Annotation 2020-07-24 044503

### PR DESCRIPTION
**Pull request by ironng**
A request to create a new deposit without a lot size selected can
occur if the user refreshes on the /deposit/new page. In this case,
redirect the user to /deposit to select a lot size.

(Also addresses a previous review nit.)

Closes #294

### CODE REVIEW

File: src/sagas/deposit.js [hunk 1]
```diff
@@ -166,10 +166,7 @@ export function* restoreRedemptionState() {
     yield* restoreState(REDEMPTION_STEP_MAP, "redemption")
 }
 
-export function* onStateRestored(depositState) {
-    /** @type {TBTC} */
-    const tbtc = yield TBTCLoaded
```
Comment (Shadowfiend) [inline src/sagas/deposit.js:171]: 🎊

File: src/sagas/deposit.js [hunk 2]
```diff
@@ -215,6 +212,13 @@ export function* requestADeposit() {
     let deposit
     try {
         const lotSizeInBtc = yield select(state => state.deposit.lotSize)
+
+        // If lot size is null, redirect user to start over
+        if (!lotSizeInBtc) {
+            yield put(navigateTo('/deposit'))
```
Comment (Shadowfiend) [inline src/sagas/deposit.js:218]: 💪
