### PR TITLE
fix etherscan link for redemption TXs

### LINKED ISSUE #295: Redemption step 6/6 "View your transaction" button have wrong link
`View your transaction` button have wrong link
image

### PR DESCRIPTION
**Pull request by brandoncurtis**
closes #295

### CODE REVIEW

File: src/components/redemption/Congratulations.js [hunk 1]
```diff
@@ -36,8 +36,8 @@ const Congratulations = ({ chainId, depositAddress }) => {
 }
 
 const mapStateToProps = (state) => ({
-  depositAddress: state.deposit.depositAddress,
-  chainId: state.tbtc.chainId,
+  depositAddress: state.redemption.depositAddress,
+  chainId: state.tbtc.web3.chainId,
```
Comment (Shadowfiend) [inline src/components/redemption/Congratulations.js:40]: Looks like we probably need to make this change to `deposit/Congratulations.js` as well, perhaps?

**Comment by ironng** [comment]
@brandoncurtis Looks like your commits aren't signed. We can merge after taking care of this! :)

**Comment by Shadowfiend** [comment]
I'm going to force the merge anyway; that commit looks good.
